version: 2
updates:
    - package-ecosystem: npm
      open-pull-requests-limit: 2
      directory: "/frontend"
      schedule:
          interval: "daily"
    - package-ecosystem: gradle
      open-pull-requests-limit: 2
      directory: "/server"
      schedule:
          interval: "daily"
